platform :ios, '7.0'
xcodeproj 'ZulaLibrary/ZulaLibrary.xcodeproj'
pod 'AFNetworking', '~> 1.3.4'
pod 'SVProgressHUD', '~> 1.0'
pod 'SDSegmentedControl', '~> 1.0.2'
pod 'MSPullToRefreshController', :git => 'https://github.com/laplacesdemon/MSPullToRefreshController.git'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.0.3'
pod 'FFCircularProgressView', '>= 0.4'
pod 'SWRevealViewController', '~> 1.1.3'
pod 'MBProgressHUD', '0.8'
