platform :ios, '6.0'
xcodeproj 'ZulaLibrary/ZulaLibrary.xcodeproj'
pod 'AFNetworking', '~> 1.3.2'
pod 'SVProgressHUD'
pod 'SSToolkit'
pod 'CocoaLumberjack'
pod 'MWPhotoBrowser', :git => 'https://github.com/yakubbaev/MWPhotoBrowser.git'
pod 'SDSegmentedControl'
pod 'MSPullToRefreshController'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SDWebImage-ProgressView'
pod 'FFCircularProgressView', '>= 0.1'
pod 'SWRevealViewController'
